# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('mid_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('work_place', models.CharField(max_length=100)),
                ('phone_num', models.IntegerField()),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('mid_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bdate', models.DateField(blank=True, null=True)),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
    ]
